# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/dotnet-demoapp.csproj
    - name: Build
      run: dotnet build ./src/dotnet-demoapp.csproj  --no-restore
    
    - name: run Test
      run: dotnet test ./tests/tests.csproj --logger trx --results-directory "testresult" --collect "XPlat Code Coverage;Format=opencover" 
      continue-on-error: true
      
    - name: Official SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v2.0.1
      with:
        # Additional arguments to the sonar-scanner
        args: >
          -Dsonar.projectKey=dev_test_github
          -Dsonar.projectName=dev_test_github
          -Dsonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
          -Dsonar.cs.vstest.reportsPaths=**/*.trx
          -Dsonar.exclusions=**/bin/**,**.json,**/obj/*
#        projectBaseDir: ./src
      env:
        #BRANCH: ${{github.event.pull_request.head.ref}}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
